### ISSUE TITLE
Eksik Hamle

### ISSUE THREAD

**Issue by ihsan-ofluoglu** [emr/yy2#1]
En sağ ve en sol sütün hamle olarak gösterilmiyor. Bunu Kontrol edebilir misiniz.

**Comment by ihsan-ofluoglu** [comment]
https://github.com/emr/yy2/blob/b6beebc308b53444846b9ec366bdb46d549a5949/src/Game.js#L71 Hta buradan kaynaklı

**Comment by emr** [comment]
Teşekkürler @ali-atolye15!
